- name: install mariadb
  hosts: database
  gather_facts: true
  become: yes

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install pip3
      apt: name=python3-pip update_cache=yes cache_valid_time=3600 state=present
    - name: instal python-pymysql for python 2
      apt: name=python-pymysql update_cache=yes cache_valid_time=3600 state=present
    - name: instal pymysql for python3
      pip:
        executable: pip3
        name: pymysql
        state: present
    - name: apt key mariadb
      apt_key: 
        url: https://mariadb.org/mariadb_release_signing_key.asc 
        state: present
    - name: add mariadb apt repository
      apt_repository: 
        repo: 'deb [arch=amd64,arm64,ppc64el] http://mirror.biznetgio.com/mariadb/repo/10.6/debian buster main' 
        state: present 
        filename: mariadb 
        update_cache: yes 


    - name: Install updated mariadb
      apt: name=mariadb-server  update_cache=yes state=present
    - name: Set account mariadb
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: "nightcore"
        user: root
        check_implicit_admin: true
        password: "nightcore"
        host: localhost

    - name: create test DB
      mysql_db: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: hasyasyin
        state: present
        login_user: root
       
  